### PR TITLE
Port to 1.21.4

### PR DESCRIPTION
**Pull request by ReedGraf**
Updated to 1.21.4

### CODE REVIEW

**Comment by jaredlll08** [comment]
While I appreciate the PR, I feel more comfortable doing ports myself so I know that it works, which I've done here https://github.com/jaredlll08/Clumps/commit/55ffbef1bc11ab191c9ccf41c554a7e1de1f865d.

**Comment by ReedGraf** [comment]
So all you do is copy the code from my pull request and claim it as your own in your own commit? Did I miss something?

**Comment by jaredlll08** [comment]
I'm sorry if there was a misunderstanding, I had no intention to steal the credit and I did not even look at your PR when I was porting, only after I had ported the mod. You can see that I didn't "copy your code" due to the versions being different
```diff
-    const val FABRIC = "0.112.0+1.21.4"
+    const val FABRIC = "0.112.2+1.21.4"
-    const val FORGE = "54.0.6"
+    const val FORGE = "54.0.10"
-    const val NEO_FORGE = "21.4.23-beta"
+    const val NEO_FORGE = "21.4.33-beta"
```

To explain a bit of my porting process, I clone all of my mods, create a new `1.21.4` branch, change the versions in one of their `Versions.kt` file, test that mod, and then use that `Versions.kt` file as a reference for all my other mods while I go through them one by one, which makes porting a lot more manageable for me[^1].

This process ensures that I port all my mods at the same time without forgeting any, that they are done in the correct order (some depend on others) and that all of my mods are using a known tested version for each modloader.

I generally haven't considered accepting ports via PRs for a few years now partly due to this process, and partly due to github not allowing a PR to create a new branch when merged, which interferes with how my CI works.

When a new branch is created, my CI starts building it immediately. For me to merge this PR, I would need to manually create a `1.21.4` branch and retarget the PR to that branch instead of `1.21.3`. However, this would result in a file on `1.21.4` with build number `1`, which is essentially just the final build for `1.21.3`. 

The only other way (that I know of) for me to merge this PR, would be to checkout your repo locally, cherry pick the commit and then push it github creating the branch at the same time. This would break the process listed above and make porting my mods take a lot longer and feel a lot more tedious.

I would still have overriden all of your code to use the versions that were known tested anyway...

I'm sorry that I didn't make it clear anywhere that I don't accept ports via PR and that you spent time working on this.
I do plan to write a `CONTRIBUTING.md` file to outline this and other guidelines, however I’m still focused on porting my larger mods, so it hasn’t been a priority yet.

[^1]: https://github.com/jaredlll08/Ambient-Environment/commit/918863602232d56ab5b0ab2b3325fdccfb7e7e6b
https://github.com/jaredlll08/bigshot/commit/14d40ebbcb6d625d99a053c3206ea64c96e8dd4c
https://github.com/jaredlll08/darkrooms/commit/878b526d8710818486d38e0228a5b221a9147912
https://github.com/jaredlll08/searchables/commit/15f0c549defa2f5376c83d5c310f4a650b2afe54
https://github.com/jaredlll08/TipTheScales/commit/bc965c5bccddcc35fbf5753f10e96aa001d0f3f2
https://github.com/jaredlll08/controlling/commit/35d88c9a41e60a1369fdf3485a64d4d275a33e54

**Comment by ReedGraf** [comment]
This is quite an interesting workflow, now I understand why you closed my pull request. Sorry, if I sounded heated in my response as it wasn't my intention. I was only confused and you have answered my question! Thank you. :)

**Comment by jaredlll08** [comment]
> This is quite an interesting workflow,

I'm sure I could make it better / automated, there just isn't enough time in the day to do it all unfortunately and what I have now allows me to spend less time porting the mods

**Pull request closed without merging**
